variables:
  # CI_DEBUG_TRACE: "true"
  PROJECT_NAME: atomic
  REPO_NAME: eva
  DEV_IMAGE: ${HUB_DEV_ADDR}/${PROJECT_NAME}/${REPO_NAME}-dev-base:v1.0
  IMAGE_TAG: ${CI_COMMIT_SHA}
  TESTING_IMAGE: ${HUB_DEV_ADDR}/${PROJECT_NAME}/${REPO_NAME}:${CI_COMMIT_SHA}
  #PROD_IMAGE: ${HUB_PROD_ADDR}/${PROJECT_NAME}/${REPO_NAME}:${CI_COMMIT_TAG}
  PROD_IMAGE: ${HUB_PROD_ADDR}/c74/${REPO_NAME}:${CI_COMMIT_TAG}
  CACHE_REPO: ${CACHE_REGISTRY}/${PROJECT_NAME}_${REPO_NAME}

Build Testing Image:
  stage: build
  image:
    name: ${KANIKO_IMAGE}
    entrypoint: [""]
  script:
    - echo $HUB_DEV_AUTH | base64 -d > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination ${TESTING_IMAGE} --cache=true --cache-repo=${CACHE_REPO}
  only:
  - develop

Build Release Image:
  stage: build
  image:
    name: ${KANIKO_IMAGE}
    entrypoint: [""]
  script:
    - echo $HUB_AUTH | base64 -d > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination ${PROD_IMAGE}  --cache=true --cache-repo=${CACHE_REPO}
  only:
  - tags
