version: '3'

volumes:
    local_postgres_data: {}

services:
    # app:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     image: app_local
    #     restart: always
    #     depends_on:
    #         - postgres
    #     volumes:
    #         - .:/work
    #     environment:
    #         - POSTGRES_DSN=postgres://postgres:galaxy@postgres:5432/galaxy
    #         - SENTRY_DSN=https://4191639452fc45deb6259e1d1992a9a4@o418626.ingest.sentry.io/5423877
    #     ports:
    #       - 5000:8000
    #     command:
    #         - uvicorn
    #         - app.main:app
    #         - --reload
    #         - --host=0.0.0.0
    #         - --port=8000

    postgres:
        image: postgres:13-alpine
        ports:
            - 15432:5432
        # volumes:
        #     - local_postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=eva
            - POSTGRES_DB=eva
