version: '3'
services:

  hydra-migrate:
    image: oryd/hydra:v1.7.4
    depends_on:
      - postgres
    environment:
      - DSN=postgres://eva:eva@postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure
